
gpu: 0
dataset: CIFAR10
num_classes: 10
model: resnet18
pre_model: 0
back_target: 3
back_results: 5
malicious: 0.0
epochs: 200
attack_epoch: 3
defense: no
# vae, fld, multi_krum, flame, Rflbat, Mab_rfl, DPA, Fltrust, Dnc, Deepsight, RLR
attack_type: no
# How_backdoor
a: 0.5
clients: 100
local_bs: 64
bs: 128
lr: 0.1
momentum: 0.5
local_ep: 1
