
gpu: 0
dataset: CIFAR10
num_classes: 10
model: resnet18
pre_model: 0
back_target: 3
malicious: 0.1
epochs: 20
attack_epoch: 3
defense: 1
attack: 1
a: 0.5
clients: 100
local_bs: 64
bs: 64
lr: 0.001
momentum: 0.9
local_ep: 1
