
gpu: 0
dataset: CIFAR100
num_classes: 100
model: resnet20
pre_model: 0
back_target: 3
back_results: 5
malicious: 0.2
epochs: 200
attack_epoch: 3
defense: no
# vae, fld, multi_krum, flame, Rflbat, Mab_rfl, DPA, Fltrust, Dnc, Deepsight, RLR
attack_type: How_backdoor
# How_backdoor
a: 0.5
clients: 100
local_bs: 10
bs: 128
lr: 0.001
momentum: 0.5
local_ep: 1
