
gpu: 0
dataset: CIFAR10
num_classes: 10
model: resnet20
pre_model: 1
back_target: 3
malicious: 0.2
epochs: 10
attack_epoch: 3
defense: Flame
# FedAvg, Agg_alignins, Agg_masa, Freqfed, MAB_RFL, Foolsgold, Deepsight, Flame
attack: 1
a: 0.5
clients: 100
local_bs: 64
bs: 64
lr: 0.001
momentum: 0.9
local_ep: 1
