
gpu: 1
dataset: FashionMNIST
num_classes: 10
model: CNN_Fashion_MNIST
epochs: 20
back_target: 5
attack_type: How_backdoor
a: 1.0
attack: 1
malicious: 0
clients: 10
local_bs: 10
bs: 128
lr: 0.001
momentum: 0.5
local_ep: 5
