
gpu: 1
dataset: FashionMNIST
num_classes: 10
model: CNN_Fashion_MNIST
epochs: 50
back_target: 8
attack_type: How_backdoor
a: 1.0
attack: 1
malicious: 0
clients: 10
local_bs: 64
bs: 64
lr: 0.001
momentum: 0.5
local_ep: 5
temperature: 3.0
distill_lr: 0.01
distill_ep: 5
